import { appSchema, tableSchema } from '@nozbe/watermelondb'

export const mySchema = appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: 'tenants',
      columns: [
      { name: 'name', type: 'string' },
      { name: 'subdomain', type: 'string' },
      { name: 'email', type: 'string' },
      { name: 'phone', type: 'string' },
      { name: 'address', type: 'string' },
      { name: 'country', type: 'string' },
      { name: 'state_province', type: 'string' },
      { name: 'city', type: 'string' },
      { name: 'postal_code', type: 'string' },
      { name: 'subscription_plan', type: 'string' },
      { name: 'subscription_status', type: 'string' },
      { name: 'subscription_start_date', type: 'number' },
      { name: 'subscription_end_date', type: 'number' },
      { name: 'max_animals', type: 'number' },
      { name: 'max_users', type: 'number' },
      { name: 'timezone', type: 'string' },
      { name: 'currency', type: 'string' },
      { name: 'language', type: 'string' },
      { name: 'settings', type: 'string' },
      { name: 'is_active', type: 'boolean' },
      { name: 'created_at', type: 'number' },
      { name: 'updated_at', type: 'number' },
      { name: 'deleted_at', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'users',
      columns: [
      { name: 'tenant_id', type: 'string', isIndexed: true },
      { name: 'email', type: 'string' },
      { name: 'password_hash', type: 'string' },
      { name: 'first_name', type: 'string' },
      { name: 'last_name', type: 'string' },
      { name: 'phone', type: 'string' },
      { name: 'avatar_url', type: 'string' },
      { name: 'role', type: 'string' },
      { name: 'permissions', type: 'string' },
      { name: 'email_verified', type: 'boolean' },
      { name: 'last_login', type: 'number' },
      { name: 'reset_token', type: 'string' },
      { name: 'reset_token_expires', type: 'number' },
      { name: 'is_active', type: 'boolean' },
      { name: 'created_at', type: 'number' },
      { name: 'updated_at', type: 'number' },
      { name: 'deleted_at', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'breeds',
      columns: [
      { name: 'code', type: 'string' },
      { name: 'name', type: 'string' },
      { name: 'description', type: 'string' },
      { name: 'origin_country', type: 'string' },
      { name: 'typical_weight_range', type: 'string' },
      { name: 'characteristics', type: 'string' },
      { name: 'is_active', type: 'boolean' },
      { name: 'created_at', type: 'number' },
      { name: 'updated_at', type: 'number' },
      { name: 'deleted_at', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'medications',
      columns: [
      { name: 'code', type: 'string' },
      { name: 'commercial_name', type: 'string' },
      { name: 'generic_name', type: 'string' },
      { name: 'category', type: 'string' },
      { name: 'presentation', type: 'string' },
      { name: 'withdrawal_period_days', type: 'number' },
      { name: 'dosage_instructions', type: 'string' },
      { name: 'manufacturer', type: 'string' },
      { name: 'is_active', type: 'boolean' },
      { name: 'created_at', type: 'number' },
      { name: 'updated_at', type: 'number' },
      { name: 'deleted_at', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'vaccines',
      columns: [
      { name: 'code', type: 'string' },
      { name: 'name', type: 'string' },
      { name: 'disease', type: 'string' },
      { name: 'type', type: 'string' },
      { name: 'manufacturer', type: 'string' },
      { name: 'application_route', type: 'string' },
      { name: 'dosage', type: 'string' },
      { name: 'booster_required', type: 'boolean' },
      { name: 'booster_interval_days', type: 'number' },
      { name: 'is_active', type: 'boolean' },
      { name: 'created_at', type: 'number' },
      { name: 'updated_at', type: 'number' },
      { name: 'deleted_at', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'diseases',
      columns: [
      { name: 'code', type: 'string' },
      { name: 'name', type: 'string' },
      { name: 'scientific_name', type: 'string' },
      { name: 'category', type: 'string' },
      { name: 'severity', type: 'string' },
      { name: 'symptoms', type: 'string' },
      { name: 'treatment_protocol', type: 'string' },
      { name: 'prevention_measures', type: 'string' },
      { name: 'is_zoonotic', type: 'boolean' },
      { name: 'is_active', type: 'boolean' },
      { name: 'created_at', type: 'number' },
      { name: 'updated_at', type: 'number' },
      { name: 'deleted_at', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'facilities',
      columns: [
      { name: 'tenant_id', type: 'string', isIndexed: true },
      { name: 'code', type: 'string' },
      { name: 'name', type: 'string' },
      { name: 'facility_type', type: 'string' },
      { name: 'parent_facility_id', type: 'string', isIndexed: true },
      { name: 'capacity', type: 'number' },
      { name: 'area_sqm', type: 'number' },
      { name: 'description', type: 'string' },
      { name: 'location_description', type: 'string' },
      { name: 'coordinates', type: 'string' },
      { name: 'is_active', type: 'boolean' },
      { name: 'created_at', type: 'number' },
      { name: 'updated_at', type: 'number' },
      { name: 'deleted_at', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'pens',
      columns: [
      { name: 'tenant_id', type: 'string', isIndexed: true },
      { name: 'facility_id', type: 'string', isIndexed: true },
      { name: 'code', type: 'string' },
      { name: 'name', type: 'string' },
      { name: 'capacity', type: 'number' },
      { name: 'area_sqm', type: 'number' },
      { name: 'has_feeder', type: 'boolean' },
      { name: 'has_waterer', type: 'boolean' },
      { name: 'has_climate_control', type: 'boolean' },
      { name: 'notes', type: 'string' },
      { name: 'is_active', type: 'boolean' },
      { name: 'created_at', type: 'number' },
      { name: 'updated_at', type: 'number' },
      { name: 'deleted_at', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'animals',
      columns: [
      { name: 'tenant_id', type: 'string', isIndexed: true },
      { name: 'internal_code', type: 'string' },
      { name: 'electronic_id', type: 'string', isIndexed: true },
      { name: 'visual_id', type: 'string', isIndexed: true },
      { name: 'breed_id', type: 'string', isIndexed: true },
      { name: 'sex', type: 'string' },
      { name: 'birth_date', type: 'number' },
      { name: 'birth_weight', type: 'number' },
      { name: 'mother_id', type: 'string', isIndexed: true },
      { name: 'father_id', type: 'string', isIndexed: true },
      { name: 'genetic_line', type: 'string' },
      { name: 'current_status', type: 'string' },
      { name: 'stage', type: 'string' },
      { name: 'current_pen_id', type: 'string', isIndexed: true },
      { name: 'entry_date', type: 'number' },
      { name: 'purpose', type: 'string' },
      { name: 'origin', type: 'string' },
      { name: 'acquisition_cost', type: 'number' },
      { name: 'notes', type: 'string' },
      { name: 'custom_fields', type: 'string' },
      { name: 'is_active', type: 'boolean' },
      { name: 'created_at', type: 'number' },
      { name: 'updated_at', type: 'number' },
      { name: 'deleted_at', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'weight_records',
      columns: [
      { name: 'tenant_id', type: 'string', isIndexed: true },
      { name: 'animal_id', type: 'string', isIndexed: true },
      { name: 'weight_kg', type: 'number' },
      { name: 'measurement_date', type: 'number' },
      { name: 'age_days', type: 'number' },
      { name: 'recorded_by', type: 'string' },
      { name: 'notes', type: 'string' },
      { name: 'created_at', type: 'number' },
      { name: 'updated_at', type: 'number' },
      { name: 'deleted_at', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'animal_movements',
      columns: [
      { name: 'tenant_id', type: 'string', isIndexed: true },
      { name: 'animal_id', type: 'string', isIndexed: true },
      { name: 'movement_type', type: 'string' },
      { name: 'from_pen_id', type: 'string', isIndexed: true },
      { name: 'to_pen_id', type: 'string', isIndexed: true },
      { name: 'movement_date', type: 'number' },
      { name: 'reason', type: 'string' },
      { name: 'notes', type: 'string' },
      { name: 'recorded_by', type: 'string' },
      { name: 'created_at', type: 'number' },
      { name: 'updated_at', type: 'number' },
      { name: 'deleted_at', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'batches',
      columns: [
      { name: 'tenant_id', type: 'string', isIndexed: true },
      { name: 'code', type: 'string' },
      { name: 'name', type: 'string' },
      { name: 'batch_type', type: 'string' },
      { name: 'start_date', type: 'number' },
      { name: 'expected_end_date', type: 'number' },
      { name: 'actual_end_date', type: 'number' },
      { name: 'initial_count', type: 'number' },
      { name: 'current_count', type: 'number' },
      { name: 'target_weight', type: 'number' },
      { name: 'notes', type: 'string' },
      { name: 'status', type: 'string' },
      { name: 'created_at', type: 'number' },
      { name: 'updated_at', type: 'number' },
      { name: 'deleted_at', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'batch_animals',
      columns: [
      { name: 'tenant_id', type: 'string', isIndexed: true },
      { name: 'batch_id', type: 'string', isIndexed: true },
      { name: 'animal_id', type: 'string', isIndexed: true },
      { name: 'join_date', type: 'number' },
      { name: 'exit_date', type: 'number' },
      { name: 'exit_reason', type: 'string' },
      { name: 'created_at', type: 'number' },
      { name: 'updated_at', type: 'number' },
      { name: 'deleted_at', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'breeding_services',
      columns: [
      { name: 'tenant_id', type: 'string', isIndexed: true },
      { name: 'female_id', type: 'string', isIndexed: true },
      { name: 'service_date', type: 'number' },
      { name: 'service_type', type: 'string' },
      { name: 'male_id', type: 'string', isIndexed: true },
      { name: 'semen_batch', type: 'string' },
      { name: 'semen_provider', type: 'string' },
      { name: 'heat_detection_method', type: 'string' },
      { name: 'technician_id', type: 'string', isIndexed: true },
      { name: 'notes', type: 'string' },
      { name: 'created_at', type: 'number' },
      { name: 'updated_at', type: 'number' },
      { name: 'deleted_at', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'pregnancies',
      columns: [
      { name: 'tenant_id', type: 'string', isIndexed: true },
      { name: 'animal_id', type: 'string', isIndexed: true },
      { name: 'breeding_service_id', type: 'string', isIndexed: true },
      { name: 'confirmation_date', type: 'number' },
      { name: 'confirmation_method', type: 'string' },
      { name: 'expected_farrowing_date', type: 'number' },
      { name: 'actual_farrowing_date', type: 'number' },
      { name: 'pregnancy_status', type: 'string' },
      { name: 'notes', type: 'string' },
      { name: 'created_at', type: 'number' },
      { name: 'updated_at', type: 'number' },
      { name: 'deleted_at', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'farrowings',
      columns: [
      { name: 'tenant_id', type: 'string', isIndexed: true },
      { name: 'pregnancy_id', type: 'string', isIndexed: true },
      { name: 'mother_id', type: 'string', isIndexed: true },
      { name: 'farrowing_date', type: 'number' },
      { name: 'piglets_born_alive', type: 'number' },
      { name: 'piglets_born_dead', type: 'number' },
      { name: 'piglets_mummified', type: 'number' },
      { name: 'total_litter_weight', type: 'number' },
      { name: 'average_piglet_weight', type: 'number' },
      { name: 'assistance_required', type: 'boolean' },
      { name: 'assistance_type', type: 'string' },
      { name: 'complications', type: 'string' },
      { name: 'attended_by', type: 'string' },
      { name: 'notes', type: 'string' },
      { name: 'created_at', type: 'number' },
      { name: 'updated_at', type: 'number' },
      { name: 'deleted_at', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'weanings',
      columns: [
      { name: 'tenant_id', type: 'string', isIndexed: true },
      { name: 'farrowing_id', type: 'string', isIndexed: true },
      { name: 'weaning_date', type: 'number' },
      { name: 'piglets_weaned', type: 'number' },
      { name: 'average_weaning_weight', type: 'number' },
      { name: 'age_at_weaning_days', type: 'number' },
      { name: 'mortality_during_lactation', type: 'number' },
      { name: 'notes', type: 'string' },
      { name: 'recorded_by', type: 'string' },
      { name: 'created_at', type: 'number' },
      { name: 'updated_at', type: 'number' },
      { name: 'deleted_at', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'health_records',
      columns: [
      { name: 'tenant_id', type: 'string', isIndexed: true },
      { name: 'animal_id', type: 'string', isIndexed: true },
      { name: 'batch_id', type: 'string', isIndexed: true },
      { name: 'record_type', type: 'string' },
      { name: 'record_date', type: 'number' },
      { name: 'disease_id', type: 'string', isIndexed: true },
      { name: 'symptoms', type: 'string' },
      { name: 'diagnosis', type: 'string' },
      { name: 'temperature', type: 'number' },
      { name: 'treatment_plan', type: 'string' },
      { name: 'prognosis', type: 'string' },
      { name: 'veterinarian_id', type: 'string', isIndexed: true },
      { name: 'notes', type: 'string' },
      { name: 'created_at', type: 'number' },
      { name: 'updated_at', type: 'number' },
      { name: 'deleted_at', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'vaccinations',
      columns: [
      { name: 'tenant_id', type: 'string', isIndexed: true },
      { name: 'animal_id', type: 'string', isIndexed: true },
      { name: 'batch_id', type: 'string', isIndexed: true },
      { name: 'vaccine_id', type: 'string', isIndexed: true },
      { name: 'application_date', type: 'number' },
      { name: 'dosage', type: 'string' },
      { name: 'application_route', type: 'string' },
      { name: 'batch_number', type: 'string' },
      { name: 'expiration_date', type: 'number' },
      { name: 'next_dose_date', type: 'number' },
      { name: 'administered_by', type: 'string' },
      { name: 'notes', type: 'string' },
      { name: 'created_at', type: 'number' },
      { name: 'updated_at', type: 'number' },
      { name: 'deleted_at', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'medication_treatments',
      columns: [
      { name: 'tenant_id', type: 'string', isIndexed: true },
      { name: 'animal_id', type: 'string', isIndexed: true },
      { name: 'batch_id', type: 'string', isIndexed: true },
      { name: 'health_record_id', type: 'string', isIndexed: true },
      { name: 'medication_id', type: 'string', isIndexed: true },
      { name: 'start_date', type: 'number' },
      { name: 'end_date', type: 'number' },
      { name: 'dosage', type: 'string' },
      { name: 'frequency', type: 'string' },
      { name: 'application_route', type: 'string' },
      { name: 'withdrawal_date', type: 'number' },
      { name: 'administered_by', type: 'string' },
      { name: 'notes', type: 'string' },
      { name: 'created_at', type: 'number' },
      { name: 'updated_at', type: 'number' },
      { name: 'deleted_at', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'mortality_records',
      columns: [
      { name: 'tenant_id', type: 'string', isIndexed: true },
      { name: 'animal_id', type: 'string', isIndexed: true },
      { name: 'death_date', type: 'number' },
      { name: 'age_at_death_days', type: 'number' },
      { name: 'weight_at_death', type: 'number' },
      { name: 'death_cause', type: 'string' },
      { name: 'disease_id', type: 'string', isIndexed: true },
      { name: 'necropsy_performed', type: 'boolean' },
      { name: 'necropsy_findings', type: 'string' },
      { name: 'disposal_method', type: 'string' },
      { name: 'recorded_by', type: 'string' },
      { name: 'notes', type: 'string' },
      { name: 'created_at', type: 'number' },
      { name: 'updated_at', type: 'number' },
      { name: 'deleted_at', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'feed_types',
      columns: [
      { name: 'tenant_id', type: 'string', isIndexed: true },
      { name: 'code', type: 'string' },
      { name: 'name', type: 'string' },
      { name: 'category', type: 'string' },
      { name: 'protein_percentage', type: 'number' },
      { name: 'energy_mcal_kg', type: 'number' },
      { name: 'crude_fiber_percentage', type: 'number' },
      { name: 'formula', type: 'string' },
      { name: 'manufacturer', type: 'string' },
      { name: 'cost_per_kg', type: 'number' },
      { name: 'is_active', type: 'boolean' },
      { name: 'created_at', type: 'number' },
      { name: 'updated_at', type: 'number' },
      { name: 'deleted_at', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'feed_inventory',
      columns: [
      { name: 'tenant_id', type: 'string', isIndexed: true },
      { name: 'feed_type_id', type: 'string', isIndexed: true },
      { name: 'current_stock_kg', type: 'number' },
      { name: 'minimum_stock_kg', type: 'number' },
      { name: 'maximum_stock_kg', type: 'number' },
      { name: 'last_purchase_date', type: 'number' },
      { name: 'last_purchase_price', type: 'number' },
      { name: 'created_at', type: 'number' },
      { name: 'updated_at', type: 'number' },
      { name: 'deleted_at', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'feed_movements',
      columns: [
      { name: 'tenant_id', type: 'string', isIndexed: true },
      { name: 'feed_type_id', type: 'string', isIndexed: true },
      { name: 'movement_type', type: 'string' },
      { name: 'quantity_kg', type: 'number' },
      { name: 'movement_date', type: 'number' },
      { name: 'unit_cost', type: 'number' },
      { name: 'total_cost', type: 'number' },
      { name: 'supplier', type: 'string' },
      { name: 'invoice_number', type: 'string' },
      { name: 'notes', type: 'string' },
      { name: 'recorded_by', type: 'string' },
      { name: 'created_at', type: 'number' },
      { name: 'updated_at', type: 'number' },
      { name: 'deleted_at', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'feed_consumption',
      columns: [
      { name: 'tenant_id', type: 'string', isIndexed: true },
      { name: 'consumption_date', type: 'number' },
      { name: 'pen_id', type: 'string', isIndexed: true },
      { name: 'batch_id', type: 'string', isIndexed: true },
      { name: 'animal_id', type: 'string', isIndexed: true },
      { name: 'feed_type_id', type: 'string', isIndexed: true },
      { name: 'quantity_kg', type: 'number' },
      { name: 'number_of_animals', type: 'number' },
      { name: 'recorded_by', type: 'string' },
      { name: 'notes', type: 'string' },
      { name: 'created_at', type: 'number' },
      { name: 'updated_at', type: 'number' },
      { name: 'deleted_at', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'transaction_categories',
      columns: [
      { name: 'tenant_id', type: 'string', isIndexed: true },
      { name: 'code', type: 'string' },
      { name: 'name', type: 'string' },
      { name: 'type', type: 'string' },
      { name: 'parent_category_id', type: 'string', isIndexed: true },
      { name: 'is_active', type: 'boolean' },
      { name: 'created_at', type: 'number' },
      { name: 'updated_at', type: 'number' },
      { name: 'deleted_at', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'financial_transactions',
      columns: [
      { name: 'tenant_id', type: 'string', isIndexed: true },
      { name: 'transaction_date', type: 'number' },
      { name: 'transaction_type', type: 'string' },
      { name: 'category_id', type: 'string', isIndexed: true },
      { name: 'amount', type: 'number' },
      { name: 'currency', type: 'string' },
      { name: 'description', type: 'string' },
      { name: 'animal_id', type: 'string', isIndexed: true },
      { name: 'batch_id', type: 'string', isIndexed: true },
      { name: 'payment_method', type: 'string' },
      { name: 'invoice_number', type: 'string' },
      { name: 'supplier_customer', type: 'string' },
      { name: 'notes', type: 'string' },
      { name: 'recorded_by', type: 'string' },
      { name: 'created_at', type: 'number' },
      { name: 'updated_at', type: 'number' },
      { name: 'deleted_at', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'animal_sales',
      columns: [
      { name: 'tenant_id', type: 'string', isIndexed: true },
      { name: 'sale_date', type: 'number' },
      { name: 'customer_name', type: 'string' },
      { name: 'customer_contact', type: 'string' },
      { name: 'total_amount', type: 'number' },
      { name: 'payment_status', type: 'string' },
      { name: 'payment_method', type: 'string' },
      { name: 'invoice_number', type: 'string' },
      { name: 'notes', type: 'string' },
      { name: 'recorded_by', type: 'string' },
      { name: 'created_at', type: 'number' },
      { name: 'updated_at', type: 'number' },
      { name: 'deleted_at', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'animal_sale_details',
      columns: [
      { name: 'tenant_id', type: 'string', isIndexed: true },
      { name: 'sale_id', type: 'string', isIndexed: true },
      { name: 'animal_id', type: 'string', isIndexed: true },
      { name: 'weight_kg', type: 'number' },
      { name: 'price_per_kg', type: 'number' },
      { name: 'unit_price', type: 'number' },
      { name: 'quantity', type: 'number' },
      { name: 'subtotal', type: 'number' },
      { name: 'created_at', type: 'number' },
      { name: 'updated_at', type: 'number' },
      { name: 'deleted_at', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'tasks',
      columns: [
      { name: 'tenant_id', type: 'string', isIndexed: true },
      { name: 'title', type: 'string' },
      { name: 'description', type: 'string' },
      { name: 'task_type', type: 'string' },
      { name: 'priority', type: 'string' },
      { name: 'status', type: 'string' },
      { name: 'assigned_to', type: 'string' },
      { name: 'due_date', type: 'number' },
      { name: 'due_time', type: 'number' },
      { name: 'completed_date', type: 'number' },
      { name: 'facility_id', type: 'string', isIndexed: true },
      { name: 'pen_id', type: 'string', isIndexed: true },
      { name: 'animal_id', type: 'string', isIndexed: true },
      { name: 'batch_id', type: 'string', isIndexed: true },
      { name: 'recurrence_rule', type: 'string' },
      { name: 'notes', type: 'string' },
      { name: 'created_by', type: 'string' },
      { name: 'created_at', type: 'number' },
      { name: 'updated_at', type: 'number' },
      { name: 'deleted_at', type: 'number' },
      ]
    }),
  ]
})